### PR TITLE
IMPROVE: add trap and set -e

### PR DESCRIPTION
**Pull request by elops**
This will ensure errors are not ignored and cleanup function
  is invoked if anything bad happens.

### CODE REVIEW

**Comment by scalp42** [comment]
Hi @elops 

Thanks for the contribution. I'm a little reserved about setting `-e` (regarding curl for example), because _any_ subcommand or pipeline that returns a non-zero status will cause the shell to exit.

I assume you've been using this script, do you think you could give it another review to make sure there should be a zero status on every command if you have the time ?

If not, I'll spin up a centos box and go through every call to be sure.

Have you been running this script with `-e` ?

Thanks for the feedback!

**Comment by elops** [comment]
Hello scalp42,

Indeed it will exit but when I ran it for instance script was failing at

``` bash
yum -q check-update
```

And just kept going and finally failed afterwards on some other checked part. I never got it to successfully install python2.7 for me :( . So I figured better error checking would help exit/terminate in right place.

cheers,
Elops

**Comment by scalp42** [comment]
@elops 

`yum -q check-update` should definitely not fail.

Could you provide me more feedback please ? Version of CentOS? Arch? Host (VPS maybe?) ?

Thanks in advance!

I'm a little busy with work but I'm hoping to get this merged this weekend.

**Comment by elops** [comment]
@scalp42 
It's VPS, has CentOS 5.10 installed, arch x86_64

``` bash
# yum -q check-update

alpine.x86_64                                                                                           2.03-1.el5                                                                                       epel     
cppunit.x86_64                                                                                          1.12.0-4.el5.1                                                                                   epel     
cpuspeed.x86_64                                                                                         1:1.2.1-11.el5_10                                                                                updates  
device-mapper-multipath.x86_64                                                                          0.4.7-59.el5_10.2                                                                                updates  
fltk.x86_64                                                                                             1.1.9-4.el5                                                                                      epel     
fping.x86_64                                                                                            3.10-1.el5.rf                                                                                    rpmforge 
fribidi.x86_64                                                                                          0.19.2-2.el5                                                                                     epel     
git.x86_64                                                                                              1.8.2.1-1.el5                                                                                    epel     
id3lib.i386                                                                                             3.8.3-20.el5                                                                                     epel     
id3lib.x86_64                                                                                           3.8.3-20.el5                                                                                     epel     
id3lib-devel.x86_64                                                                                     3.8.3-20.el5                                                                                     epel     
jasper.x86_64                                                                                           1.900.1-14.el5                                                                                   epel     
jasper-devel.x86_64                                                                                     1.900.1-14.el5                                                                                   epel     
koan.noarch                                                                                             2.4.4-1.el5                                                                                      epel     
kpartx.x86_64                                                                                           0.4.7-59.el5_10.2                                                                                updates  
libid3tag.x86_64                                                                                        0.15.1b-5.el5                                                                                    epel     
librsync.x86_64                                                                                         0.9.7-13.el5                                                                                     epel     
librsync-devel.x86_64                                                                                   0.9.7-13.el5                                                                                     epel     
libsndfile.x86_64                                                                                       1.0.17-5.el5                                                                                     epel     
openldap.i386                                                                                           2.3.43-28.el5_10                                                                                 updates  
openldap.x86_64                                                                                         2.3.43-28.el5_10                                                                                 updates  
openldap-devel.i386                                                                                     2.3.43-28.el5_10                                                                                 updates  
openldap-devel.x86_64                                                                                   2.3.43-28.el5_10                                                                                 updates  
perl-Class-Loader.noarch                                                                                2.03-5.el5                                                                                       epel     
perl-Convert-ASCII-Armour.noarch                                                                        1.4-5.el5                                                                                        epel     
perl-Convert-BinHex.noarch                                                                              1.119-5.el5                                                                                      epel     
perl-Convert-PEM.noarch                                                                                 0.07-5.el5                                                                                       epel     
perl-Crypt-DH.noarch                                                                                    0.06-9.el5                                                                                       epel     
perl-Crypt-Primes.noarch                                                                                0.50-4.el5                                                                                       epel     
perl-Crypt-Random.noarch                                                                                1.25-4.el5                                                                                       epel     
perl-Data-Buffer.noarch                                                                                 0.04-5.el5                                                                                       epel     
perl-DateTime.x86_64                                                                                    1:0.41-1.el5                                                                                     epel     
perl-Digest-MD2.x86_64                                                                                  2.03-9.el5                                                                                       epel     
perl-Email-Date-Format.noarch                                                                           1.002-4.el5                                                                                      epel     
perl-Expect.noarch                                                                                      1.21-4.el5                                                                                       epel     
perl-ExtUtils-ParseXS.noarch                                                                            2.2206-1.el5                                                                                     epel     
perl-File-MMagic.noarch                                                                                 1.27-2.el5                                                                                       epel     
perl-File-Tail.noarch                                                                                   0.99.3-5.el5.1                                                                                   epel     
perl-GDGraph.noarch                                                                                     1:1.44-1.el5                                                                                     epel     
perl-GDTextUtil.noarch                                                                                  0.86-8.el5                                                                                       epel     
perl-Git.x86_64                                                                                         1.8.2.1-1.el5                                                                                    epel     
perl-HTML-FormatText-WithLinks.noarch                                                                   0.14-1.el5                                                                                       epel     
perl-HTML-Template.noarch                                                                               2.9-1.el5.2                                                                                      epel     
perl-HTML-Tree.noarch                                                                                   1:3.23-9.el5                                                                                     epel     
perl-IO-stringy.noarch                                                                                  2.110-5.el5                                                                                      epel     
perl-IPC-Run3.noarch                                                                                    0.043-4.el5                                                                                      epel     
perl-LWP-Authen-Wsse.noarch                                                                             0.05-2.el5.1                                                                                     epel     
perl-List-MoreUtils.x86_64                                                                              0.33-5.el5                                                                                       epel     
perl-MIME-Base32.noarch                                                                                 1.02a-1.el5                                                                                      epel     
perl-MIME-tools.noarch                                                                                  5.420-3.el5                                                                                      epel     
perl-Mail-Sendmail.noarch                                                                               0.79-9.el5.1                                                                                     epel     
perl-Math-BigInt-GMP.x86_64                                                                             1.24-5.el5                                                                                       epel     
perl-Math-GMP.x86_64                                                                                    2.05-2.el5                                                                                       epel     
perl-Module-Signature.noarch                                                                            0.73-1.el5                                                                                       epel     
perl-Net-SSH-Perl.noarch                                                                                1.34-2.el5                                                                                       epel     
perl-Number-Compare.noarch                                                                              0.01-8.el5                                                                                       epel     
perl-Pod-Escapes.noarch                                                                                 1.04-5.el5                                                                                       epel     
perl-Probe-Perl.noarch                                                                                  0.01-4.el5                                                                                       epel     
perl-Sort-Versions.noarch                                                                               1.5-7.el5                                                                                        epel     
perl-Test-Script.noarch                                                                                 1.06-1.el5.1                                                                                     epel     
perl-Text-Glob.noarch                                                                                   0.08-2.el5                                                                                       epel     
perl-Try-Tiny.noarch                                                                                    0.11-4.el5                                                                                       epel     
perl-common-sense.noarch                                                                                3.5-1.el5                                                                                        epel     
perl-version.x86_64                                                                                     1:0.7203-1.el5                                                                                   epel     
tzdata.x86_64                                                                                           2014b-3.24.el5                                                                                   updates  
xorg-x11-server-Xvfb.x86_64                                                                             1.1.1-48.101.0.1.el5.centos.3                                                                    updates  
Obsoleting Packages
OpenEXR.x86_64                                                                                          1.4.0a-5.el5                                                                                     epel     
    openexr.x86_64                                                                                      1.4.0a-1.el5.rf                                                                                  installed
# echo $?
100

```

**Comment by scalp42** [comment]
@elops 

Sorry for late update. That error code is just that there are some updates available in yum.

It should not be considered as an error, that's why I'm reluctant in merging this.

**Comment by elops** [comment]
no worries ;-)

**Pull request closed without merging**
